if (NOT DEFINED VSAG_SOURCE_DIR)
    message (FATAL_ERROR "VSAG_SOURCE_DIR is required")
endif ()

include (${VSAG_SOURCE_DIR}/cmake/VSAGThirdPartyOverride.cmake)

if (TEST_UNDEFINED_URLS)
    vsag_resolve_thirdparty_override (FMT 10.2.1 missing_urls)
else ()
    set (fixture_urls default-one default-two)
    vsag_resolve_thirdparty_override (FMT 10.2.1 fixture_urls)
endif ()
list (GET fixture_urls 0 selected_url)
if (DEFINED ENV{VSAG_THIRDPARTY_FMT_10_2_1})
    set (expected_url "$ENV{VSAG_THIRDPARTY_FMT_10_2_1}")
    set (expected_source pinned)
elseif (DEFINED ENV{VSAG_THIRDPARTY_FMT})
    set (expected_url "$ENV{VSAG_THIRDPARTY_FMT}")
    set (expected_source legacy)
else ()
    set (expected_url default-one)
    set (expected_source default)
endif ()
if (NOT selected_url STREQUAL expected_url)
    message (FATAL_ERROR "The selected URL does not match the expected source")
endif ()
message (STATUS "TEST_SELECTION=${expected_source}")

if (DEFINED TEST_EXPECTED_HASH)
    file (DOWNLOAD "${selected_url}" "${TEST_DOWNLOAD_PATH}"
          EXPECTED_HASH "${TEST_EXPECTED_HASH}" STATUS download_status LOG download_log)
    list (GET download_status 0 download_result)
    if (NOT download_result EQUAL 0)
        message (FATAL_ERROR "Override hash verification failed: ${download_status}")
    endif ()
endif ()
